export const GET_ALL_VALUES_LOAD  = " GET_ALL_VALUES_LOAD";
export const GET_ALL_VALUES_SUCCESS  = "GET_ALL_VALUES_SUCCESS ";
export const  GET_ALL_VALUES_FAIL  = " GET_ALL_VALUES_FAIL ";
export const  ADD_KILOETCONSO  = " ADD_KILOETCONSO ";
export const  DELETE_KILOETCONSO = " DELETE_KILOETCONSO ";
export const  GET_KILOETCONSO = " GET_KILOETCONSO ";
export const  EDIT_KILOETCONSO = " EDIT_KILOETCONSO ";
export const  CURRENT_KILOETCONSO = " CURRENT_KILOETCONSO ";